networks:
  internal_network:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: unless-stopped
    # ports:
    #   - "6379:6379"
    networks:
      - internal_network
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    restart: unless-stopped
    # ports:
    #   - "8000:8000"
    depends_on:
      - redis
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health]"]
      interval: 10s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8083:80"
    depends_on:
      - fastapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal_network
